### ISSUE TITLE
staticIota is not visible.

### ISSUE THREAD

**Issue by yuy-m** [evenex/universal#1]
> universal-0.1.0\universal\source\core\product.d(89,23): Deprecation: std.typecons.staticIota(int beg, int end) is not visible from module product

Access specifier of `template staticIota` is `package`.

**Comment by vl-01** [comment]
Haven't looked at this repo in awhile; turns out not to compile with the gdc at all anymore (D evolves quickly). I'll need to do quite a bit of updating; as a stopgap, replacing the definition of `Iota` at that line with
```
template Iota(size_t N) {
    import std.range: iota;
    import std.meta: aliasSeqOf;
    alias Iota = aliasSeqOf!(N.iota);
}
```
(adapted from [here](http://forum.dlang.org/post/o2euib$21ii$1@digitalmars.com))

ought to work.

**Comment by vl-01** [comment]
Finally got around to updating to a recent DMD release, and applied this fix.
